name: Linear Regressor E2E

on: [push]

jobs:
  package-install:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10
    steps:
      - uses: actions/checkout@v2
      - name: Install Linear Regressor
        run: |
          make install
          python3 -c "import linear_regressor; print(linear_regressor.__name__)"

  style-checks:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          make setup-ci-dev
      - name: Run Style Checks
        run: |
          make check-style-all

  pytest-coverage:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: |
          make setup-ci-dev
      - name: Run Tests and Coverage
        run: |
          make test-coverage

  # build-push-server:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     # - name: Login to DockerHub
  #     #   uses: docker/login-action@v1
  #     #   with:
  #     #     username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     #     password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     - name: Build # and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: false
  #         tags: linear_regressor_server:latest

  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing Server
        run: make test-serving
